services:
    Sidus\EAVModelBundle\Serializer\Denormalizer\EAVDataDenormalizer:
        parent: serializer.normalizer.object
        arguments:
            - '@Sidus\EAVModelBundle\Registry\FamilyRegistry'
            - '@Doctrine\Common\Persistence\ManagerRegistry'
            - '@Sidus\EAVModelBundle\Serializer\EntityProviderInterface'
            - '%sidus_eav_model.denormalizer.data.ignored_attributes%'
        tags:
            - { name: serializer.normalizer, priority: 9 }
