parameters:
    eavmanager_user.normalizer.user.ignored_attributes:
        - password
        - plainPassword
        - salt
        - authenticationToken
        - rawRoles
        - combinedFamilyPermissions

services:
    CleverAge\EAVManager\UserBundle\Serializer\Normalizer\UserNormalizer:
        parent: serializer.normalizer.object
        arguments:
            - '@Sidus\EAVModelBundle\Serializer\MaxDepthHandler'
            - '@Sidus\EAVModelBundle\Serializer\ByReferenceHandler'
        calls:
            - [setIgnoredAttributes, ['%eavmanager_user.normalizer.user.ignored_attributes%']]
        tags:
            - { name: serializer.normalizer, priority: 10 }

    Sidus\EAVModelBundle\Serializer\Normalizer\Flat\FlatNormalizer:
        arguments:
            - '@CleverAge\EAVManager\UserBundle\Serializer\Normalizer\UserNormalizer'
            - [csv]
        tags:
            - { name: serializer.normalizer, priority: 11 }
