# Imports all default values for the EAV Manager to work

imports:
    # Default parameters
    - { resource: base_config/parameters.yml }

    # Admin
    - { resource: base_config/admin/* }

    # Application
    - { resource: base_config/application/* }

    # DataGrid
    - { resource: base_config/datagrid/* }

    # Model
    - { resource: base_config/model/* }
