services:
    Symfony\Component\Security\Core\Authorization\Voter\RoleHierarchyVoter:
        alias: security.access.role_hierarchy_voter

    CleverAge\EAVManager\SecurityBundle\Voter\FamilyVoter:
        public: false
        autowire: true
        tags:
            - { name: security.voter }

    CleverAge\EAVManager\SecurityBundle\Voter\EAVDataVoter:
        public: false
        autowire: true
        tags:
            - { name: security.voter }

    CleverAge\EAVManager\SecurityBundle\Voter\UserVoter:
        public: false
        autowire: true
        tags:
            - { name: security.voter }

    CleverAge\EAVManager\SecurityBundle\Voter\GroupVoter:
        public: false
        autowire: true
        tags:
        - { name: security.voter }
