services:
    eavmanager_api_platform.normalizer.base.attribute:
        class: CleverAge\EAVManager\ApiPlatformBundle\Serializer\Normalizer\BaseApiNormalizer
        parent: api_platform.serializer.normalizer.item
        calls:
            - [setNormalizer, ['@sidus_eav_model.normalizer.attribute']]
        tags:
            - { name: serializer.normalizer, priority: 1 }

    # JsonLD Support
    eavmanager_api_platform.normalizer.json_ld.attribute:
        class: CleverAge\EAVManager\ApiPlatformBundle\Serializer\Normalizer\JsonLdApiNormalizer
        parent: api_platform.jsonld.normalizer.item
        calls:
            - [setNormalizer, ['@sidus_eav_model.normalizer.attribute']]
        tags:
            - { name: serializer.normalizer, priority: 9 }
