sidus_eav_model:
    collection_type: Sidus\EAVBootstrapBundle\Form\Type\BootstrapCollectionType

mopa_bootstrap:
    icons:
        icon_set: fontawesome4
    form:
        layout: false
        render_required_asterisk: true
        render_optional_text: false
        help_label:
            tooltip:
                icon: info-circle
            popover:
                icon: info-circle

sidus_admin:
    base_template: '@CleverAgeEAVManagerLayout/layout.html.twig'
