services:
    Sidus\EAVFilterBundle\Filter\Type\DateRangeFilterType:
        public: false
        arguments:
            - date_range
            - Sidus\EAVBootstrapBundle\Form\Type\DateRangeType
        calls:
            - [setFallbackFilterType, ['@Sidus\FilterBundle\Filter\Type\Doctrine\DateRangeFilterType']]
        tags:
            - { name: sidus.filter_type }

    Sidus\FilterBundle\Filter\Type\Doctrine\DateRangeFilterType:
        public: false
        arguments:
            - date_range
            - Sidus\EAVBootstrapBundle\Form\Type\DateRangeType
        tags:
            - { name: sidus.filter_type }
