services:
    CleverAge\EAVManager\AdminBundle\Form\Type\AdminLinkType:
        public: false
        autowire: true
        tags:
          - { name: form.type }

    CleverAge\EAVManager\AdminBundle\Form\Type\AdminLink:
        public: false
        autowire: true
        tags:
            - { name: form.type }

    CleverAge\EAVManager\AdminBundle\Form\Type\ImageType:
        public: false
        autowire: true
        tags:
          - { name: form.type }

    CleverAge\EAVManager\AdminBundle\Form\Type\EmbedMultiFamilyEntryType:
        public: false
        arguments:
            - '@Sidus\BaseBundle\Doctrine\RepositoryFinder'
            - '%sidus_eav_model.entity.data.class%'
        tags:
            - { name: form.type }

    CleverAge\EAVManager\AdminBundle\Form\Type\DataGridColumnType:
        public: false
        autowire: true
        tags:
            - { name: form.type }

    CleverAge\EAVManager\AdminBundle\Form\Type\DataGridType:
        public: false
        autowire: true
        tags:
            - { name: form.type }

    CleverAge\EAVManager\AdminBundle\Form\Extension\DataSelectorTypeExtension:
        public: false
        arguments:
            - Sidus\EAVModelBundle\Form\Type\SimpleDataSelectorType
        tags:
            - { name: form.type_extension, extended_type: Sidus\EAVModelBundle\Form\Type\SimpleDataSelectorType }

    CleverAge\EAVManager\AdminBundle\Form\Extension\LinkTypeExtension:
        public: false
        arguments:
            - Sidus\DataGridBundle\Form\Type\LinkType
        tags:
            - { name: form.type_extension, extended_type: Sidus\DataGridBundle\Form\Type\LinkType }
