services:
    CleverAge\EAVManager\AdminBundle\Form\FormHelper:
        public: false
        autowire: true

    CleverAge\EAVManager\AdminBundle\Form\EAVFormHelper:
        public: false
        autowire: true

    CleverAge\EAVManager\AdminBundle\Templating\TemplatingHelper:
        public: false
        autowire: true

    CleverAge\EAVManager\AdminBundle\Templating\EAVTemplatingHelper:
        public: false
        autowire: true

    CleverAge\EAVManager\AdminBundle\DataGrid\DataGridHelper:
        public: false
        autowire: true

    CleverAge\EAVManager\AdminBundle\DataGrid\EAVDataGridHelper:
        public: false
        autowire: true
