sidus_admin:
    configurations:
        _data:
            entity: '%sidus_data_class%'
            controller_pattern:
                - 'CleverAge\EAVManager\AdminBundle\Action\EAV\{{Action}}Action'
            template_pattern:
                - '@CleverAgeEAVManagerAdmin/EAVData/{{action}}.{{format}}.twig'
                - '@CleverAgeEAVManagerAdmin/Base/{{action}}.{{format}}.twig'
            form_type: '%eav_form.type%'
            prefix: /_data
            actions:
                create:
                    path: /create/{familyCode}
                read:
                    path: /read/{id}
                edit:
                    path: /edit/{id}
                delete:
                    path: /delete/{id}
                preview:
                    path: /preview/{id}
                    defaults:
                        _controller: CleverAge\EAVManager\AdminBundle\Action\EAV\ReadAction
                    form_options:
                        layout: horizontal
                attributeDataGrid:
                    path: /
            options:
                hidden: true
