<?php
/*
 * This file is part of the CleverAge/EAVManager package.
 *
 * Copyright (c) 2015-2018 Clever-Age
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace CleverAge\EAVManager\SecurityBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FamilyPermissionRepository.
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 *
 * @author Vincent Chalnot <vchalnot@clever-age.com>
 */
class FamilyPermissionRepository extends EntityRepository
{
}
