<?php

namespace CleverAge\EAVManager\SecurityBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FamilyPermissionRepository.
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class FamilyPermissionRepository extends EntityRepository
{
}
