<?php

namespace CleverAge\EAVManager\ProcessBundle\Task;

use CleverAge\EAVManager\ImportBundle\Model\CsvFile;
use CleverAge\EAVManager\ProcessBundle\Model\ProcessState;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * Reads the file path from configuration and iterates over it
 * Ignores any input
 */
class CsvWriterTask extends AbstractCsvTask
{
    /**
     * @param ProcessState $processState
     *
     * @throws \Symfony\Component\OptionsResolver\Exception\ExceptionInterface
     */
    public function execute(ProcessState $processState)
    {
        $options = $this->getOptions($processState);
        try {
            if (!$this->csv instanceof CsvFile) {
                $this->initFile($options);
            }
            $this->csv->writeLine($processState->getInput());
        } catch (\Exception $e) {
            $processState->stop($e);
        }
    }

    /**
     * @param OptionsResolver $resolver
     *
     * @throws \Symfony\Component\OptionsResolver\Exception\AccessException
     * @throws \Symfony\Component\OptionsResolver\Exception\UndefinedOptionsException
     */
    protected function configureOptions(OptionsResolver $resolver)
    {
        parent::configureOptions($resolver); // TODO: Change the autogenerated stub*
        $resolver->setDefaults(
            [
                'mode' => 'w',
            ]
        );
    }
}
